# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newtest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblimage = QtWidgets.QLabel(self.centralwidget)
        self.lblimage.setGeometry(QtCore.QRect(0, 0, 1151, 871))
        self.lblimage.setAutoFillBackground(False)
        self.lblimage.setText("")
        self.lblimage.setPixmap(QtGui.QPixmap("12323123.jpg"))
        self.lblimage.setScaledContents(True)
        self.lblimage.setObjectName("lblimage")
        self.imageload = QtWidgets.QLabel(self.centralwidget)
        self.imageload.setGeometry(QtCore.QRect(230, 180, 271, 461))
        self.imageload.setFrameShape(QtWidgets.QFrame.Panel)
        self.imageload.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imageload.setLineWidth(5)
        self.imageload.setText("")
        self.imageload.setScaledContents(True)
        self.imageload.setObjectName("imageload")
        self.btnload = QtWidgets.QPushButton(self.centralwidget)
        self.btnload.setGeometry(QtCore.QRect(270, 660, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnload.setFont(font)
        self.btnload.setAutoFillBackground(False)
        self.btnload.setStyleSheet("background-color: rgb(255, 170, 255)")
        self.btnload.setObjectName("btnload")
        self.lblkq = QtWidgets.QLabel(self.centralwidget)
        self.lblkq.setGeometry(QtCore.QRect(520, 180, 191, 61))
        self.lblkq.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.lblkq.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblkq.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblkq.setLineWidth(5)
        self.lblkq.setText("")
        self.lblkq.setObjectName("lblkq")
        self.lblPhanTram = QtWidgets.QLabel(self.centralwidget)
        self.lblPhanTram.setGeometry(QtCore.QRect(520, 270, 191, 61))
        self.lblPhanTram.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 0);")
        self.lblPhanTram.setFrameShape(QtWidgets.QFrame.Panel)
        self.lblPhanTram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lblPhanTram.setLineWidth(5)
        self.lblPhanTram.setText("")
        self.lblPhanTram.setObjectName("lblPhanTram")
        self.btnPhanTich = QtWidgets.QPushButton(self.centralwidget)
        self.btnPhanTich.setGeometry(QtCore.QRect(560, 660, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnPhanTich.setFont(font)
        self.btnPhanTich.setAutoFillBackground(False)
        self.btnPhanTich.setStyleSheet("background-color: rgb(255, 255, 127)")
        self.btnPhanTich.setObjectName("btnPhanTich")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 600, 431, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.raise_()
        self.lblimage.raise_()
        self.imageload.raise_()
        self.btnload.raise_()
        self.lblkq.raise_()
        self.lblPhanTram.raise_()
        self.btnPhanTich.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnload.setText(_translate("MainWindow", "Load image"))
        self.btnPhanTich.setText(_translate("MainWindow", "Phân loại"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
